site_name: Zennio Remote (RU)
site_url: https://knxtrade.github.io/zr-manual-ru/
site_author: KNX-TRADE
copyright: Copyright &copy; MMXXV - KNX-TRADE by ABASTA LLC
theme:
  name: material
  language: ru
  favicon: images/favicon.svg
  logo: images/logo.png
  palette:
    primary: green
  font:
    text: "Open Sans"
    code: "Victor Mono"
  features:
    - search.suggest
    - search.highlight
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - md_in_html
  - tables
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang: 
        - ru
        - en
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
nav:
  - Введение:
    - index.md
    - intro/install.md
  - Доступ и регистрация:
    - access_register/register.md
    - access_register/login.md
    - access_register/guest_access.md
  - Устройства:
    - devices/device_pairing.md
    - devices/list_devices.md
    - devices/device_management.md
    - devices/multiple_devices_management.md
    - devices/notification.md
    - devices/device_vs_remote_control.md
  - Голосовое управление:
    - voice_control/device_management.md
    - voice_control/device_types.md
    - voice_control/assistants.md
  - Пользовательская настройка:
    - user_config/user.md
    - user_config/preferences.md
  - Помощь:
    - help/index.md
    - help/about.md
    - help/translation.md
    - help/links.md
