site_name: Zennio Remote (RU)
site_url: https://knxtrade.github.io/zr-manual-ru/
theme:
  name: material
  language: ru
  favicon: images/favicon.svg
  logo: images/logo.png
  palette:
    primary: green
  font:
    test: "Roboto Mono"
    code: "Roboto Mono"
  features:
    - search.suggest
    - search.highlight
site_author: KNX-TRADE
copyright: Copyright &copy; 2025 - KNX-TRADE от имени ABASTA LLC
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - tables
  - pymdownx.blocks.caption
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
plugins:
  - blog
  - search
nav:
  - Введение:
    - index.md
    - intro/install.md
  - Доступ и регистрация:
    - access_register/register.md
    - access_register/login.md
    - access_register/guest_access.md
  - Устройства:
    - devices/device_pairing.md
    - devices/device_management.md
    - devices/multiple_devices_management.md
    - devices/notification.md
    - devices/device_vs_remote_control.md
  - Голосовое управление:
    - voice_control/device_management.md
    - voice_control/device_types.md
    - voice_control/assistants.md
  - Пользовательская настройка:
    - user_config/user.md
    - user_config/preferences.md
  - Помощь:
    - help/index.md
    - help/about.md
